/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SystemAdminWorkAreaJPanel;

import Business.Network.Network;
import Business.WorkFlowSystem;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yuanchanglee
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {

    private JTable networkTable;
    private JTextField nameField;
    private JButton submitButton;
    private WorkFlowSystem system;
    /**
     * Creates new form ManageNetworkJPanel
     */
    
    public ManageNetworkJPanel(WorkFlowSystem system) {
          this.system = system;
          customizeComponents();
          populateNetworkTable();
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customizeComponents() {
        // 設置主面板佈局
        setLayout(new BorderLayout());
        setBackground(Color.decode("#E8EEF1")); // 柔和藍灰色背景

        // ======= 上部表格區域 =======
        JPanel tablePanel = new JPanel(new BorderLayout());
        tablePanel.setBackground(Color.decode("#E8EEF1"));

        // 表格標題
        JLabel tableLabel = new JLabel("Network Table", SwingConstants.CENTER);
        tableLabel.setFont(new Font("Arial", Font.BOLD, 24));
        tablePanel.add(tableLabel, BorderLayout.NORTH);

        // 表格
        networkTable = new JTable(new DefaultTableModel(
                new Object[][]{}, // 空表格數據
                new String[]{"Network Name"} // 表頭
        ));
        networkTable.setRowHeight(18); // 調整行高
        networkTable.setPreferredScrollableViewportSize(new Dimension(500, 100)); // 限制表格顯示大小
        JScrollPane scrollPane = new JScrollPane(networkTable);
        tablePanel.add(scrollPane, BorderLayout.CENTER);

        add(tablePanel, BorderLayout.NORTH);

        // ======= 下部表單區域 =======
        JPanel formPanel = new JPanel();
        formPanel.setLayout(new GridBagLayout());
        formPanel.setBackground(Color.decode("#E8EEF1"));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10); // 設置間距

        // ======= 表單字段 =======
        // Network Name
        JLabel nameLabel = new JLabel("Network Name:");
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.LINE_END;
        formPanel.add(nameLabel, gbc);

        nameField = new JTextField(15);
        gbc.gridx = 1;
        gbc.anchor = GridBagConstraints.LINE_START;
        formPanel.add(nameField, gbc);

        // Submit Button
        submitButton = new JButton("Submit");
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.CENTER;
        formPanel.add(submitButton, gbc);

        submitButton.addActionListener(evt -> addNetwork());

        add(formPanel, BorderLayout.CENTER);
    }

    private void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) networkTable.getModel();
        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network.getName();
            model.addRow(row);
        }
    }

    private void addNetwork() {
        String networkName = nameField.getText().trim();

        if (networkName.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Network name cannot be empty.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        Network network = system.createAndAddNetwork();
        network.setName(networkName);
        populateNetworkTable();

        javax.swing.JOptionPane.showMessageDialog(this, "Network added successfully.", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        nameField.setText(""); // 清空輸入欄
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
