/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SystemAdminWorkAreaJPanel;

import Business.WorkFlowSystem;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import ui.MainJFrame;


/**
 *
 * @author yuanchanglee
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {


    private JButton logoutButton;
    private JPanel rightPanel; // 右側顯示區域
    private WorkFlowSystem system;
    private JPanel userProcessContainer;
    private MainJFrame mainFrame; // 新增 MainJFrame 的引用
    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, WorkFlowSystem system, MainJFrame mainFrame) {
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        this.mainFrame = mainFrame;
        customizeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

   private void customizeComponents() {
        setLayout(new BorderLayout());
        setBackground(Color.decode("#F5F5F5"));

        // ======= 頂部標籤區域 =======
        // JPanel topPanel = new JPanel();
        // JLabel selectedNodeLabel = new JLabel("Selected Node: Networks");
        // selectedNodeLabel.setFont(new Font("Arial", Font.BOLD, 14)); // 設置標籤字體
        // topPanel.add(selectedNodeLabel); // 添加標籤到頂部面板
        // add(topPanel, BorderLayout.NORTH); // 添加頂部面板到主面板

        // ======= 左側導航按鈕區域 =======
        JPanel leftPanel = new JPanel();
        leftPanel.setLayout(new BoxLayout(leftPanel, BoxLayout.Y_AXIS)); // 垂直佈局
        leftPanel.setPreferredSize(new Dimension(250, 0)); // 固定寬度200px
        leftPanel.setBackground(Color.decode("#F5F5F5")); // 統一左側背景色

        Dimension buttonSize = new Dimension(220, 40);

        // 創建按鈕
        JButton manageNetworkButton = createButton("Manage Network", e -> showManageNetwork(), buttonSize);
        JButton manageEnterpriseButton = createButton("Manage Enterprise", e -> showManageEnterprise(), buttonSize);
        JButton manageAdminButton = createButton("Manage Enterprise Employee", e -> showManageEnterpriseAdmin(), buttonSize);
        logoutButton = createButton("Logout", e -> logout(), buttonSize); // 添加 Logout 按鈕

        leftPanel.add(Box.createVerticalStrut(20));
        leftPanel.add(manageNetworkButton);
        leftPanel.add(Box.createVerticalStrut(10));
        leftPanel.add(manageEnterpriseButton);
        leftPanel.add(Box.createVerticalStrut(10));
        leftPanel.add(manageAdminButton);
        leftPanel.add(Box.createVerticalGlue()); // 添加彈性空間
        leftPanel.add(logoutButton); // 將 Logout 按鈕放置於左側底部

        add(leftPanel, BorderLayout.WEST); // 添加左側導航面板到主面板

        // ======= 中間顯示區域 =======
        rightPanel = new JPanel(new CardLayout()); // 使用 CardLayout 管理內容
        rightPanel.setBackground(Color.LIGHT_GRAY); // 默認背景色
        add(rightPanel, BorderLayout.CENTER); // 添加右側顯示區域
    }

    private JButton createButton(String text, java.awt.event.ActionListener actionListener, Dimension size) {
        JButton button = new JButton(text);
        button.setAlignmentX(Component.CENTER_ALIGNMENT); // 按鈕居中
        button.addActionListener(actionListener);
        button.setPreferredSize(size);
        button.setMaximumSize(size);
        return button;
    }

    private void showManageNetwork() {
        ManageNetworkJPanel manageNetworkPanel = new ManageNetworkJPanel(system);
        rightPanel.add("ManageNetworkJPanel", manageNetworkPanel);

        // 切換到 ManageNetworkJPanel
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.show(rightPanel, "ManageNetworkJPanel");
    }

    private void showManageEnterprise() {
        ManageEnterpriseJPanel manageEnterprisePanel = new ManageEnterpriseJPanel(userProcessContainer,system);
        rightPanel.add("ManageEnterpriseJPanel", manageEnterprisePanel);

        // 切換到 ManageEnterpriseJPanel
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.show(rightPanel, "ManageEnterpriseJPanel");
    }

    private void showManageEnterpriseAdmin() {
        ManageEnterpriseEmployeeJPanel manageEnterpriseAdminPanel = new ManageEnterpriseEmployeeJPanel(system);
        rightPanel.add("ManageEnterpriseEmployeeJPanel", manageEnterpriseAdminPanel);

        // 切換到 ManageEnterpriseEmployeeJPanel
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.show(rightPanel, "ManageEnterpriseEmployeeJPanel");
    }

    private void logout() {
        // 調用 MainJFrame 的 showLoginPanel 方法切換回登入界面
        mainFrame.showLoginPanel();
        javax.swing.JOptionPane.showMessageDialog(this, "You have been successfully logged out.");
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
